# Generated by Django 5.1.6 on 2025-03-21 09:22

import apps.core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avatar_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('cover_art_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('album_type', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('copyright', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Artist'), ('performer', 'Performer Artist'), ('writer', 'Writer Artist'), ('featured', 'Featured Artist'), ('producer', 'Producer'), ('composer', 'Composer'), ('other', 'Other')], default='primary', max_length=50)),
            ],
        ),
    ]
