# Generated by Django 5.1.6 on 2025-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastepisode',
            old_name='duration_seconds',
            new_name='duration_ms',
        ),
        migrations.AddField(
            model_name='podcaster',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
