# Generated by Django 5.1.6 on 2025-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_google_url',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
