# Generated by Django 5.1.6 on 2025-03-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcategory',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='podcasts.podcast'),
        ),
        migrations.AlterUniqueTogether(
            name='podcastcategory',
            unique_together={('podcast', 'category')},
        ),
    ]
