# Generated by Django 5.1.6 on 2025-03-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
        ('podcasts', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlisttrackpodcast',
            name='added_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_playlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlisttrackpodcast',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlisttrackpodcast',
            name='podcast_ep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_playlists', to='podcasts.podcastepisode'),
        ),
        migrations.AddField(
            model_name='playlisttrackpodcast',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_playlists', to='tracks.track'),
        ),
    ]
