# Generated by Django 5.1.6 on 2025-04-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artistpick_playlist'),
        ('interactions', '0003_folder_alter_userfollowedplaylist_folder_playlist_and_more'),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlisttrackpodcast',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlisttrackpodcast',
            name='added_by_user',
        ),
        migrations.RemoveField(
            model_name='playlisttrackpodcast',
            name='podcast_ep',
        ),
        migrations.RemoveField(
            model_name='playlisttrackpodcast',
            name='track',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistTrackPodcast',
        ),
    ]
