# Generated by Django 5.1.6 on 2025-03-21 09:22

import apps.core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('popularity', models.IntegerField(default=0)),
                ('audio_file_path', models.FileField(blank=True, upload_to=apps.core.utils.generate_unique_filename)),
                ('isrc_code', models.CharField(blank=True, max_length=50)),
                ('explicit', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('plain_lyrics', models.TextField(blank=True)),
                ('synced_lyrics', models.FileField(blank=True, upload_to=apps.core.utils.generate_unique_filename)),
                ('record_label', models.CharField(blank=True, max_length=255)),
                ('is_instrumental', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tracks', to='artists.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Artist'), ('featured', 'Featured Artist'), ('remixer', 'Remixer'), ('composer', 'Composer'), ('producer', 'Producer'), ('co-producer', 'Co-Producer'), ('executive', 'Executive Producer'), ('engineer', 'Engineer'), ('mixer', 'Mixer'), ('writer', 'Writer Artist, Both Music and Lyrics'), ('writer_music', 'Music'), ('writer_lyrics', 'Lyrics'), ('performer', 'Performer Artist'), ('lead', 'Lead Vocalist'), ('backing', 'Backing Vocalist'), ('instrumentalist', 'Instrumentalist'), ('other', 'Other')], default='primary', max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_credits', to='artists.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credited_artists', to='tracks.track')),
            ],
            options={
                'unique_together': {('artist', 'track', 'role')},
            },
        ),
    ]
