# Generated by Django 5.1.6 on 2025-04-15 12:21

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='avatar_url',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils.generate_unique_filename),
        ),
    ]
