# Generated by Django 5.1.6 on 2025-03-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_initial'),
        ('interactions', '0001_initial'),
        ('playlists', '0001_initial'),
        ('podcasts', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowedartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowedplaylist',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='playlists.folder'),
        ),
        migrations.AddField(
            model_name='userfollowedplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='userfollowedplaylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowedpodcast',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='podcasts.podcast'),
        ),
        migrations.AddField(
            model_name='userfollowedpodcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersavedalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='albums.album'),
        ),
        migrations.AddField(
            model_name='usersavedalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersavedepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='podcasts.podcastepisode'),
        ),
        migrations.AddField(
            model_name='usersavedepisode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_episodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersavedtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tracks.track'),
        ),
        migrations.AddField(
            model_name='usersavedtrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowedartist',
            unique_together={('user', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowedplaylist',
            unique_together={('user', 'playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowedpodcast',
            unique_together={('user', 'podcast')},
        ),
        migrations.AlterUniqueTogether(
            name='usersavedalbum',
            unique_together={('user', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='usersavedepisode',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='usersavedtrack',
            unique_together={('user', 'track')},
        ),
    ]
