# Generated by Django 5.1.6 on 2025-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_folder_alter_userfollowedplaylist_folder_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='PlaylistTrackPodcast',
        ),
    ]
