# Generated by Django 5.1.6 on 2025-03-21 09:22

import apps.core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('thumbnail_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('popularity', models.IntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('more_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Artist image galleries',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtistPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True)),
                ('image_url', models.ImageField(upload_to=apps.core.utils.generate_unique_filename)),
                ('external_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
