# Generated by Django 5.1.6 on 2025-03-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_initial'),
        ('artists', '0001_initial'),
        ('playlists', '0001_initial'),
        ('podcasts', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistimagegallery',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_picks', to='albums.album'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_picks', to='podcasts.podcastepisode'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_picks', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_picks', to='podcasts.podcast'),
        ),
        migrations.AddField(
            model_name='artistpick',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_picks', to='tracks.track'),
        ),
    ]
